### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by paddyroddy** [reproducibleMATLAB/matlab-project-template#13]

**Comment by davidwyld** [comment]
There will be two README files:
* `.github/README.md` - the template's readme, rendered on github
* `README.md` - the ultimate project's readme


`README.md` should include some placeholders for users to fill in:
 - [ ] dependencies
 - [ ] matlab version
 - [ ] how to run
 - [ ] what data is required

**Comment by dc2917** [comment]
The .github/README.md should contain a note about licensing
